name: Deploy Docker Container to EC2

on:
  push:
    branches:
      - main

deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push   # Wait for the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Logging into DockerHub..."
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

            echo "Pulling latest image..."
            docker pull dhankhar9918/flip-kart-app:mariov1

            echo "Stopping and removing old container (if exists)..."
            docker stop flipkart-container || true
            docker rm flipkart-container || true

            echo "Running NEW container..."
            docker run -d --name flipkart-container -p 8080:8080 dhankhar9918/flip-kart-app:mariov1
          EOF
